version: '3'
services:
  db:
    image: 204065533127.dkr.ecr.ap-northeast-1.amazonaws.com/mysql:latest
    container_name: chatbot_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=iii
    volumes:
      - ./Chatbot_Dev/mysql_data:/var/lib/mysql
      - ./Chatbot_Dev/mysql_init:/docker-entrypoint-initdb.d/

  api:
    image: 204065533127.dkr.ecr.ap-northeast-1.amazonaws.com/api:latest
    container_name: chatbot_api
    user: root
    environment:
      - GRANT_SUDO=yes
    ports:
      - "5001:5000"
    depends_on:
      - db
    links:
      - db
    volumes:
      - ./Chatbot_Dev/code:/home/jovyan/work/
    command: python /home/jovyan/work/code.py

  redis:
    image: 204065533127.dkr.ecr.ap-northeast-1.amazonaws.com/redis:latest
    container_name: chatbot_redis
    ports:
     - "6379:6379"
    volumes:
     - ./Chatbot_Line/redis/data:/data
#     - ./Chatbot_Line/redis/redis.config:/usr/local/etc/redis/redis.conf

  jupyter-tutorial:
    image: 204065533127.dkr.ecr.ap-northeast-1.amazonaws.com/jupyter:latest
    container_name: chatbot_jupyter
    env_file:
      - ./ip.env
    depends_on: 
      - api
      - redis
    ports:
      - "8888:8888"
      - "5000:5000"
    volumes:
     - ./Chatbot_Line/code:/home/jovyan/work
#    command: start-notebook.sh --NotebookApp.token=''
    command: python /home/jovyan/work/test.py

  ngrok-external-dns:
    image: 204065533127.dkr.ecr.ap-northeast-1.amazonaws.com/ngrok:latest
    container_name: chatbot_ngrok
    depends_on: 
      - jupyter-tutorial
    ports:
      - "4040:4040"
    command: ngrok http chatbot_ubuntu:5000

#  jupyter-tutorial:
#    image: 204065533127.dkr.ecr.ap-northeast-1.amazonaws.com/jupyter:latest
#    container_name: chatbot_jupyter
#    depends_on: 
#      - api
#      - redis
#    ports:
#      - "8888:8888"
#      - "5000:5000"
#    volumes:
#      - ./Chatbot_Line/code:/home/jovyan/work
#    command: python /home/jovyan/work/test.py
